name: maths_vision
description: App For Combine Maths Students

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0+19

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.5
  charcode: ^1.3.1
  wakelock: ^0.6.2
  flutter_windowmanager: ^0.2.0
  http: ^0.13.5
  provider: ^6.0.4
  percent_indicator: ^4.2.2
  tab_indicator_styler: ^2.0.0
  flutter_math_fork: ^0.6.3+1
  url_launcher: ^6.1.6
  shape_of_view: ^1.0.2
  loading_animations: ^2.2.0
  loading_animation_widget: ^1.2.0+3
  share: ^2.0.4
  cloud_firestore: ^4.0.4
  clip_shadow: ^0.2.1
  icon_shadow: ^1.0.1
  countdown_timer_simple: ^1.0.2
  stop_watch_timer: ^2.0.0
  cached_network_image: ^3.2.2
  connectivity: ^3.0.6
  internet_connection_checker: ^1.0.0+1
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  external_path: ^1.0.3
  shimmer: ^2.0.0
  date_time_picker: ^2.1.0
  scroll_snap_list: ^0.9.1
  shared_preferences: ^2.0.15
  google_sign_in: ^5.4.2
  google_fonts: ^3.0.1
  youtube_player_flutter: ^8.1.1
  flutter_blurhash: ^0.7.0
  flutter_rating_bar: ^4.0.1
  flutter_downloader: ^1.9.0
  fluttertoast: ^8.1.1
  flutter_speed_dial: ^6.2.0
  flutter_facebook_auth: ^5.0.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  firebase_storage: ^11.0.4
  firebase_app_check: ^0.1.1+3
  firebase_core_platform_interface: 4.5.2
  google_mobile_ads: ^2.3.0
  in_app_purchase:
  firebase_messaging:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: Abhaya Libre
      fonts:
        - asset: fonts/AbhayaLibre-Regular.ttf

    - family: Iskola Potha
      fonts:
        - asset: fonts/iskpota.ttf

    - family: Bhashitha
      fonts:
        - asset: fonts/AdBhashitha.otf

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Italic.ttf

    - family: Warna
      fonts:
        - asset: fonts/WARNA.ttf

    - family: Typo Round Demo
      fonts:
        - asset: fonts/Typo_Round_Bold_Demo.otf

    - family: Matura Script
      fonts:
        - asset: fonts/MATURASC.ttf

    - family: Gothic
      fonts:
        - asset: fonts/Century_Gothic.ttf

    - family: Copperplate Gothic
      fonts:
        - asset: fonts/Copperplate_Gothic_Bold_Regular.ttf

    - family: Copperplate Gothic Light
      fonts:
        - asset: fonts/CopperplateGothicLight.ttf

    - family: Colonna MT
      fonts:
        - asset: fonts/ColonnaMT.ttf

    - family: Blenda Script
      fonts:
        - asset: fonts/Blenda_Script.otf

    - family: Perpeta
      fonts:
        - asset: fonts/perpeta.ttf

    - family: Javanese Text
      fonts:
        - asset: fonts/javatext.ttf

    - family: Imprint MT Shadow
      fonts:
        - asset: fonts/ImprintMTShadow.ttf

    - family: Perpetua Bold
      fonts:
        - asset: fonts/PerpetuaBold.ttf

    - family: Rockwell
      fonts:
        - asset: fonts/Rockwell.otf

    - family: Lucida Fax Italic
      fonts:
        - asset: fonts/Lucida_Fax_Italic.ttf

    - family: Lucida Console
      fonts:
        - asset: fonts/Lucida_Console.ttf

    - family: Lucida Bright Italic
      fonts:
        - asset: fonts/lucidabrightitalic.ttf

    - family: Lucida Bright
      fonts:
        - asset: fonts/LUCIDA.ttf

    - family: Forte
      fonts:
        - asset: fonts/Forte.ttf

    - family: Brush
      fonts:
        - asset: fonts/BRUSHSCI.ttf

    - family: OCR A
      fonts:
        - asset: fonts/OCRA.ttf

    - family: Scriptina
      fonts:
        - asset: fonts/scriptina-regular.ttf

    - family: AgencyFB Bold
      fonts:
        - asset: fonts/AgencyFB-Bold.ttf

    - family: AgencyFB
      fonts:
        - asset: fonts/agency-fb.ttf

    - family: Antipasto Pro Extralight
      fonts:
        - asset: fonts/AntipastoPro-Extralight.ttf

    - family: Niagara Solid
      fonts:
        - asset: fonts/NIAGSOL.ttf

    - family: Lemon Jelly
      fonts:
        - asset: fonts/Lemon_Jelly.ttf

    - family: Gadugi
      fonts:
        - asset: fonts/gadugi.ttf

    - family: Arial
      fonts:
        - asset: fonts/arial.ttf

    - family: Aquire
      fonts:
        - asset: fonts/AquireLight.otf

    - family: Aquire Bold
      fonts:
        - asset: fonts/AquireBold.otf

    - family: Poiret One
      fonts:
        - asset: fonts/PoiretOne-Regular.ttf

    - family: Potta One
      fonts:
        - asset: fonts/PottaOne-Regular.ttf

    - family: Falcon
      fonts:
        - asset: fonts/falconpunchital.ttf

    - family: Calisto MT Italic
      fonts:
        - asset: fonts/Calisto_MT_Italic.ttf

    - family: Gabriola
      fonts:
        - asset: fonts/gabriola.ttf

    - family: Baiti
      fonts:
        - asset: fonts/monbaiti.ttf

    # Roboto font can be removed
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf

    - family: Roboto Regular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: Verdana Bold
      fonts:
        - asset: fonts/Verdana_Bold.ttf

    - family: Emoji
      fonts:
        - asset: fonts/seguiemj.ttf

    - family: Segoe UI
      fonts:
        - asset: fonts/Segoe_UI.ttf

    - family: Dubai Regular
      fonts:
        - asset: fonts/Dubai_Regular.ttf

    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf

    - family: Dancing Script
      fonts:
        - asset: fonts/DancingScript.ttf

    - family: Sylfaen
      fonts:
        - asset: fonts/sylfaen.ttf

    - family: Constan
      fonts:
        - asset: fonts/constan.ttf

    - family: MontereyFLF
      fonts:
        - asset: fonts/MontereyFLF.ttf

    - family: MontereyFLF Bold Italic
      fonts:
        - asset: fonts/MontereyFLF_BoldItalic.ttf

    - family: Hey October
      fonts:
        - asset: fonts/Hey_October.ttf

    - family: Centaur
      fonts:
        - asset: fonts/CENTAUR.ttf

    - family: Juice ITC
      fonts:
        - asset: fonts/juice_itc.ttf

    - family: Pristina
      fonts:
        - asset: fonts/PRISTINA.TTF

    - family: Microsoft
      fonts:
        - asset: fonts/msuighur.ttf

    - family: Microsoft Yi Baiti
      fonts:
        - asset: fonts/msyi.ttf

    - family: Digital
      fonts:
        - asset: fonts/DIGITALDREAM.ttf

    - family: Ateeca
      fonts:
        - asset: fonts/Ateeca.ttf

    - family: Calisto MT BI
      fonts:
        - asset: fonts/CALISTBI.ttf

    - family: Ebrima
      fonts:
        - asset: fonts/ebrima.ttf

    - family: Georgia
      fonts:
        - asset: fonts/Georgia.ttf

    - family: Crash
      fonts:
        - asset: fonts/Crashnumber.ttf

    - family: Subway
      fonts:
        - asset: fonts/Subway_Black.ttf

    - family: Cambria
      fonts:
        - asset: fonts/Cambria.ttf

    - family: Perpetua Titling MT Light
      fonts:
        - asset: fonts/PERTILI.ttf

    - family: Philosopher
      fonts:
        - asset: fonts/Philosopher-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
