final List pureSubjects = [
  ["ගණිත අභ්‍යුහන මූලධර්මය", 'Mathematical Induction'],
  ["අසමානතා", 'Inequalities'],
  ["ද්විපද ප්‍රසාරණය", 'Binomial Expansion'],
  ["සීමා", 'Limits'],
  ["බහුපද ශ්‍රිත", 'Polynomial Equations'],
  ["වර්ග සමීකරණ", 'Quadratic Functions'],
  ["සංකරණ හා සං‍යෝජන", 'Permutations and Combinations'],
  ["ශ්‍රේණි", 'Series'],
  ["න්‍යාස", 'Matrices'],
  ["සංකීර්ණ සංඛ්‍යා", 'Complex Numbers'],
  ["අවකලනය", 'Differentiation'],
  ["අනුකලනය", 'Integration'],
  ["සරල රේඛාව", 'Straight Line'],
  ["වෘත්තය", 'Circle'],
  ["ත්‍රිකෝණමිතිය", 'Trigonometry'],
];

final List appliedSubjects = [
  ["ගැටුම්", 'Collisions'],
  ["ප්‍රක්ශිප්ත", 'Projectiles'],
  ["ඝර්ෂණය", 'Friction'],
  ["කාර්යය, ශක්තිය, ජවය", 'Work, Energy, Power'],
  ["දෛශික", 'Vectors'],
  ["ඒකතල බල පද්ධති", 'Coplanar Forces'],
  ["බල සමතුලිතතාවය", 'Equilibrium of Forces'],
  ["ප්‍රවේග-කාල ප්‍රස්තාර", 'Velocity-Time Graphs'],
  ["සාපේක්ෂ ප්‍රාවේගය", 'Relative Velocity'],
  ["සාපේක්ෂ ත්වරණය", 'Relative Acceleration'],
  ["වෘත්ත චලිතය", 'Circular Motion'],
  ["සරල අනුවර්තීය චලිතය", 'Simple Harmonic Motion'],
  ["රාමු සැකිලි", 'Frame Works'],
  ["සන්දි කල දඬු", 'Jointed Rods'],
  ["ගුරුත්ව කේන්ද්‍රය", 'Center of Gravity'],
  ["සම්භාවිතාව", 'Probability'],
  ["සංඛ්‍යානය", 'Statistics'],
];
