Map<String, dynamic> questions = {
  'stage1': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\tan\bm\theta}',
        'thirdLine': 'සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'\frac {\cos\theta} {\sin\theta}',
        r'\frac {\sin\theta} {\cos\theta}',
        r'\frac 1 {\sec\theta}',
        r'\frac 1 {\cos\theta}',
        r'\frac {\sec\theta} {\cosec\theta}',
      ],
      'answer': r'\frac {\sin\theta} {\cos\theta}',
      'coins': 0,
      'xp': 3,
      'answerBuyCoins': 0,
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{\cot\bm{\theta}}',
        'thirdLine': 'සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'\frac {\cos\theta} {\sin\theta}',
        r'\frac {\sin\theta} {\cos\theta}',
        r'\frac 1 {\sec\theta}',
        r'\frac 1 {\cos\theta}',
        r'\frac {\sec\theta} {\cosec\theta}',
      ],
      'answer': r'\frac {\cos\theta} {\sin\theta}',
      'coins': 0,
      'xp': 4,
      'answerBuyCoins': 0,
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{\cosec\bm{\theta}}',
        'thirdLine': 'සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'\frac 1 {\cos\theta}',
        r'\frac 1 {\sin\theta}',
        r'\frac 1 {\sec\theta}',
        r'\frac 1 {\cot\theta}',
        r'\frac 1 {\tan\theta}',
      ],
      'answer': r'\frac 1 {\sin\theta}',
      'coins': 0,
      'xp': 5,
      'answerBuyCoins': 0,
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{\sec\bm{\theta}}',
        'thirdLine': 'සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'\frac 1 {\sin\theta}',
        r'\frac 1 {\cosec\theta}',
        r'\frac {\tan\theta} {\cot\theta}',
        r'\frac 1 {\cot\theta}',
        r'\frac 1 {\cos\theta}',
      ],
      'answer': r'\frac 1 {\cos\theta}',
      'coins': 0,
      'xp': 5,
      'answerBuyCoins': 0,
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{\cot\bm{\theta}}',
        'thirdLine': 'සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'\frac {\sin\theta} {\cos\theta}',
        r'\frac 1 {\tan\theta}',
        r'\frac 1 {\cos\theta}',
        r'\frac {\sec\theta} {\cosec\theta}',
        r'\sin\theta\cos\theta',
      ],
      'answer': r'\frac 1 {\tan\theta}',
      'coins': 0,
      'xp': 8,
      'answerBuyCoins': 2,
    },
    'question6': {
      'question': {
        'firstLine': r'\mathbf{\tan\bm{\theta}\cot\bm{\theta}}',
        'thirdLine': 'සුලු කිරීමෙන් ලැබෙනුයේ පහත කුමක්ද?',
      },
      'answers': [
        r'\frac 1 {\sin\theta}',
        r'\frac 1 {\sec\theta}',
        r'1',
        r'\cos\theta',
        r'0',
      ],
      'answer': r'1',
      'coins': 0,
      'xp': 8,
      'answerBuyCoins': 2,
    },
    'question7': {
      'question': {
        'firstLine': r'\mathbf{\cot\bm{\theta}\sin\bm{\theta}}',
        'thirdLine': 'සුලු කිරීමෙන් ලැබෙනුයේ පහත කුමක්ද?',
      },
      'answers': [
        r'1',
        r'\cosec\theta',
        r'\cos\theta',
        r'\frac 1 {\sin\theta}',
        r'\frac {\sin^2\theta} {\cos\theta}',
      ],
      'answer': r'\cos\theta',
      'coins': 0,
      'xp': 10,
      'answerBuyCoins': 3,
    },
    'question8': {
      'question': {
        'firstLine': r'\mathbf{\sin\bm{\theta}\cot\bm{\theta}\sec\bm{\theta}}',
        'thirdLine': 'සුලු කිරීමෙන් ලැබෙනුයේ පහත කුමක්ද?',
      },
      'answers': [
        r'\cot\theta',
        r'\tan\theta',
        r'\sec\theta\cosec\theta',
        r'\pi',
        r'1',
      ],
      'answer': r'1',
      'coins': 0,
      'xp': 14,
      'answerBuyCoins': 4,
    },
    'question9': {
      'question': {
        'firstLine': r'\mathbf{\cosec\bm{\theta}\cot\bm{\theta}\sec\bm{\theta}}',
        'thirdLine': 'සුලු කිරීමෙන් ලැබෙනුයේ පහත කුමක්ද?',
      },
      'answers': [
        r'\frac 1 {\sin\theta}',
        r'1',
        r'\frac 1 {\cos^2\theta}',
        r'\frac 1 {\sin^2\theta}',
        r'\tan^2\theta',
      ],
      'answer': r'\frac 1 {\sin^2\theta}',
      'coins': 0,
      'xp': 18,
      'answerBuyCoins': 5,
    },
    'question10': {
      'question': {
        'firstLine':
            r'\mathbf{\frac {\tan\bm{\theta}\cosec\bm{\theta}\cos\bm{\theta}} {\cot\bm{\theta}}}',
        'thirdLine': 'සුලු කිරීමෙන් ලැබෙනුයේ පහත කුමක්ද?',
      },
      'answers': [
        r'\tan\theta',
        r'\cot\theta',
        r'\frac {\tan\theta} {\sin\theta}',
        r'1',
        r'\frac {\cos\theta} {\sec\theta}',
      ],
      'answer': r'\tan\theta',
      'coins': 0,
      'xp': 25,
      'answerBuyCoins': 9,
    },
  },
  'stage2': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\frac 1 {\tan A + \cot A}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත ප්‍රකාශ අතුරින් කුමකටද?',
      },
      'answers': [
        r'\frac 1 {\sin A\cos A}',
        r'\frac 1 {\tan A\cos A}',
        r'\sin A\cos A',
        r'\cot A\sin A',
        r'\sec A',
      ],
      'answer': r'\sin A\cos A',
      'coins': 6,
      'xp': 30,
      'answerBuyCoins': 10,
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{\frac {1 + \tan^2 A} {1 + \cot^2 A}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහතින් කුමන පදයටද?',
      },
      'answers': [
        r'\tan A',
        r'\cot A',
        r'\sec^2 A + 1',
        r'\tan^2 A',
        r'1',
      ],
      'answer': r'\tan^2 A',
      'coins': 6,
      'xp': 30,
      'answerBuyCoins': 10,
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{\cos^4 A - \sin^4 A + 1}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'2\cos^2 A',
        r'\cos^2 A',
        r'\sin^2 A',
        r'2\sin^2 A',
        r'\sin A\cos A',
      ],
      'answer': r'2\cos^2 A',
      'coins': 7,
      'xp': 36,
      'answerBuyCoins': 13,
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{\tan^2 A - \sin^2 A}',
        'thirdLine': 'මෙම ප්‍රකාශය පහතින් කුමකට සමාන වේද?',
      },
      'answers': [
        r'\cot^2 A\sin^2 A',
        r'\tan^2 A\sin^2 A',
        r'\sec^2 A - 2\cos^2 A',
        r'\sin^4 A\sec^4 A',
        r'\frac {\tan^2 A} {\cot^2 A}',
      ],
      'answer': r'\tan^2 A\sin^2 A',
      'coins': 8,
      'xp': 38,
      'answerBuyCoins': 15,
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{\frac {\cosec A} {\cot A + \tan A}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත දැක්වෙන ප්‍රකාශ අතුරින් කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'1',
        r'\cos A\sin A',
        r'\sin A',
        r'\cosec A\cot A',
        r'\cos A',
      ],
      'answer': r'\cos A',
      'coins': 8,
      'xp': 40,
      'answerBuyCoins': 15,
    },
    'question6': {
      'question': {
        'firstLine': r'\mathbf{{\frac {\sin A} {1 + \cos A}} + {\frac {1 + \cos A} {\sin A}}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'2\sin A',
        r'\cot A\cosec A',
        r'2\cosec A',
        r'\frac {1 + \sin a} {1 - \cos A}',
        r'\frac {1 - \cos a} {1 + \sin A}',
      ],
      'answer': r'2\cosec A',
      'coins': 9,
      'xp': 43,
      'answerBuyCoins': 16,
    },
    'question7': {
      'question': {
        'firstLine': r'\mathbf{{\frac {\cosec A} {\cosec A - 1}} + {\frac {\cosec A} {\cosec A + 1}}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන පදයටද?',
      },
      'answers': [
        r'2\cosec^2 A',
        r'2',
        r'2\sec^2 A',
        r'\frac 1 {2\sec^2 A}',
        r'\frac 2 {\sec^2 A}',
      ],
      'answer': r'2\sec^2 A',
      'coins': 9,
      'xp': 43,
      'answerBuyCoins': 16,
    },
    'question8': {
      'question': {
        'firstLine': r'\mathbf{\sqrt {\cosec^2 A - 1}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන පදයටද?',
      },
      'answers': [
        r'\cos A\cosec A',
        r'\cos A',
        r'\frac {1 + \sin^2 A} {\sin A}',
        r'\tan A',
        r'\sec A\sin A',
      ],
      'answer': r'\cos A\cosec A',
      'coins': 10,
      'xp': 45,
      'answerBuyCoins': 17,
    },
    'question9': {
      'question': {
        'firstLine': r'\mathbf{\sqrt {\frac {1 - \sin A} {1 + \sin A}}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\cosec A - \cot A',
        r'\sqrt {1 - \tan^2 A}',
        r'\sin A + \cos A',
        r'\sec A - \tan A',
        r'\sqrt {\sec^2 A - \tan^2 A}',
      ],
      'answer': r'\sec A - \tan A',
      'coins': 11,
      'xp': 50,
      'answerBuyCoins': 18,
    },
    'question10': {
      'question': {
        'firstLine': r'\mathbf{\sec^4 A - \sec^2 A}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත ප්‍රකාශ අතුරින් කුමකටද?',
      },
      'answers': [
        r'2\tan^4 A',
        r'(\tan^2 A - 1)^2',
        r'\sec^2 A',
        r'(\tan^2 A + 1)^2',
        r'\tan^4 A + \tan^2 A',
      ],
      'answer': r'\tan^4 A + \tan^2 A',
      'coins': 12,
      'xp': 55,
      'answerBuyCoins': 20,
    },
    'question11': {
      'question': {
        'firstLine': r'\mathbf{{\frac {\cos A} {1 - \tan A}} + {\frac {\sin A} {1 - \cot A}}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\cos A - \sin A',
        r'\sin A + \cos A',
        r'\frac 1 {\sin A - \cos A}',
        r'\frac {1 - \cot A} {1 - \tan A}',
        r'\sin^2 A - \cos^2 A',
      ],
      'answer': r'\sin A + \cos A',
      'coins': 12,
      'xp': 55,
      'answerBuyCoins': 20,
    },
    'question12': {
      'question': {
        'firstLine': r'\mathbf{\tan\bm{\theta} = \frac 1 {\sqrt 7}}',
        'secondLine': [
          'ලෙස දී ඇත්නම්',
          r'\mathbf{\frac {\cosec^2 \bm{\theta} - \sec^2 \bm{\theta}} {\cosec^2 \bm{\theta} + \sec^2 \bm{\theta}}}',
          'හි',
        ],
        'thirdLine': 'අගය පහතින් තෝරන්න.',
      },
      'answers': [
        r'\frac {3 \sqrt 7} {64}',
        r'1',
        r'\frac 3 4',
        r'\frac {4 \sqrt 3} {\sqrt 7}',
        r'\frac {\sqrt {28}} {64}',
      ],
      'answer': r'\frac 3 4',
      'coins': 14,
      'xp': 58,
      'answerBuyCoins': 22,
    },
    'question13': {
      'question': {
        'firstLine': r'\mathbf{\frac {\cot A + \tan B} {\cot B + \tan A}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\frac {\sin B + \cos A} {\cos B + \sin A}',
        r'1',
        r'\cot A\tan B',
        r'\frac {\sin B} {\cos A}',
        r'\cot B\tan A',
      ],
      'answer': r'\cot A\tan B',
      'coins': 14,
      'xp': 58,
      'answerBuyCoins': 22,
    },
    'question14': {
      'question': {
        'firstLine': r'\mathbf{2\sin\bm{\theta} = 2 - \cos\bm{\theta}}',
        'secondLine': [
          'නම්',
          r'\mathbf{\sin\bm{\theta}}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
        'forthLine': r'\Big(0<\theta<\frac \pi 2\Big)',
      },
      'answers': [
        r'\frac 4 5',
        r'1',
        r'0',
        r'\frac 3 5',
        r'\frac 2 5',
      ],
      'answer': r'\frac 3 5',
      'coins':15,
      'xp': 63,
      'answerBuyCoins': 25,
    },
    'question15': {
      'question': {
        'firstLine': r'\mathbf{(\sin A + \cosec A)^2 + (\cos A + \sec A)^2}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\cot A + \tan A + 9',
        r'\cot^2 A + \tan^2 A + 7',
        r'\sin^2 A - \cos^2 A + 5',
        r'\cot^2 A + \sin A\sec A + 3',
        r'\cosec^2 A + \sec^2 A + 1',
      ],
      'answer': r'\cot^2 A + \tan^2 A + 7',
      'coins': 16,
      'xp': 68,
      'answerBuyCoins': 28,
    },
    'question16': {
      'question': {
        'firstLine': r'\mathbf{(1 + \cot A - \cosec A)( 1 + \tan A + \sec A)}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\sin A\cos A',
        r'\frac {1 + \sin^2 A} {2\cos A}',
        r'1',
        r'2\sec A\tan A',
        r'2',
      ],
      'answer': r'2',
      'coins': 16,
      'xp': 68,
      'answerBuyCoins': 28,
    },
    'question17': {
      'question': {
        'firstLine': r'\mathbf{\tan^2\bm{\theta} + \sec\bm{\theta} = 5}',
        'secondLine': [
          'නම්',
          r'\mathbf{\cos\bm{\theta}}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
        'forthLine': r'\Big(0<\theta<\frac \pi 2\Big)',
      },
      'answers': [
        r'\frac 1 2',
        r'-3',
        r'2',
        r'1',
        r'-\frac 1 3',
      ],
      'answer': r'\frac 1 2',
      'coins':17,
      'xp': 70,
      'answerBuyCoins': 30,
    },
    'question18': {
      'question': {
        'firstLine': r'\mathbf{\frac {\cos A\cosec A - \sec A\sin A} {\cos A + \sin A}}',
        'thirdLine': 'මෙම ප්‍රකාශය පහත ප්‍රකාශ අතුරින් කුමකට සමාන වේද?',
      },
      'answers': [
        r'1',
        r'\cosec A - \sec A',
        r'\tan A - \cot A',
        r'2',
        r'\sec A - \cosec A',
      ],
      'answer': r'\cosec A - \sec A',
      'coins': 18,
      'xp': 75,
      'answerBuyCoins': 35,
    },
    'question19': {
      'question': {
        'firstLine': r'\mathbf{3\sec^4\bm{\theta} + 8 = 10\sec^2\bm{\theta}}',
        'secondLine': [
          'නම්',
          r'\mathbf{\tan\bm{\theta}}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
        'forthLine': r'\Big(0<\theta<\frac \pi 4\Big)',
      },
      'answers': [
        r'1',
        r'\frac 1 3',
        r'\frac 1 {\sqrt 3}',
        r'-\frac 1 3',
        r'-\frac 1 {\sqrt 3}',
      ],
      'answer': r'\frac 1 {\sqrt 3}',
      'coins':22,
      'xp': 80,
      'answerBuyCoins': 40,
    },
    'question20': {
      'question': {
        'firstLine': r'\mathbf{\frac {\tan A + \sec A - 1} {\tan A - \sec A + 1}}',
        'thirdLine': 'පහත ප්‍රකාශ අතුරින් මෙම ප්‍රකාශයට සමාන ප්‍රකාශය කුමක්ද?',
      },
      'answers': [
        r'\frac {1 - \sin A} {\cos A}',
        r'\frac {1 + \sin A} {2\cos A}',
        r'\cosec A + \tan A',
        r'\frac {\cos A} {\sin A + 1}',
        r'\sec A + \tan A',
      ],
      'answer': r'\sec A + \tan A',
      'coins': 30,
      'xp': 95,
      'answerBuyCoins': 50,
    },
  },
  'stage3': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\tan(180 + A)}',
        'thirdLine': 'සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'\cot A',
        r'-\tan A',
        r'-\cot A',
        r'\tan A',
        r'\tan (-A)',
      ],
      'answer': r'\tan A',
      'coins': 3,
      'xp': 15,
      'answerBuyCoins': 5,
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{\sin(270 + A)}',
        'thirdLine': 'සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'\sin A',
        r'-\cos A',
        r'-\sin A',
        r'\cos A',
        r'\sin (-A)',
      ],
      'answer': r'-\cos A',
      'coins': 4,
      'xp': 17,
      'answerBuyCoins': 6,
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{\cos \frac {2\bm{\pi}} 3}',
        'thirdLine': 'අගය සොයන්න.',
      },
      'answers': [
        r'\frac 1 2',
        r'\frac {\sqrt 3} 2',
        r'-\frac 1 2',
        r'-\frac {\sqrt 3} 2',
        r'\frac 1 {\sqrt 2}',
      ],
      'answer': r'-\frac 1 2',
      'coins': 4,
      'xp': 18,
      'answerBuyCoins': 6,
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{\tan \frac {7\bm{\pi}} 6}',
        'thirdLine': 'අගය සොයන්න.',
      },
      'answers': [
        r'\frac 1 {\sqrt 3}',
        r'\sqrt 3',
        r'-\frac 1 {\sqrt 3}',
        r'-\sqrt 3',
        r'1',
      ],
      'answer': r'\frac 1 {\sqrt 3}',
      'coins': 4,
      'xp': 18,
      'answerBuyCoins': 6,
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{\cosec \frac {7\bm{\pi}} 6}',
        'thirdLine': 'අගය පහතින් තෝරන්න',
      },
      'answers': [
        r'\frac 1 2',
        r'2',
        r'-\frac 1 2',
        r'1',
        r'-2',
      ],
      'answer': r'-2',
      'coins': 5,
      'xp': 20,
      'answerBuyCoins': 8,
    },
    'question6': {
      'question': {
        'firstLine': r'\mathbf{\sin (-65)}',
        'thirdLine': 'සමාන වනුයේ පහත කවර ප්‍රකාශයටද?',
      },
      'answers': [
        r'\sin 65',
        r'\cos 65',
        r'-\cos 25',
        r'-\sin 25',
        r'\cos (-25)',
      ],
      'answer': r'-\cos 25',
      'coins': 5,
      'xp': 23,
      'answerBuyCoins': 9,
    },
    'question7': {
      'question': {
        'firstLine': r'\mathbf{\tan (-246)}',
        'thirdLine': 'සමාන වනුයේ පහත කවර ප්‍රකාශයටද?',
      },
      'answers': [
        r'3.24',
        r'-\cot 24',
        r'-0.83',
        r'\tan 24',
        r'0.83',
      ],
      'answer': r'-\cot 24',
      'coins': 5,
      'xp': 23,
      'answerBuyCoins': 9,
    },
    'question8': {
      'question': {
        'firstLine': r'\mathbf{\cos (-928)}',
        'thirdLine': 'සමාන වනුයේ පහත සඳහන් ප්‍රකාශ අතුරින් කුමකටද?',
      },
      'answers': [
        r'-\cos 28',
        r'0.83',
        r'\sin 28',
        r'-0.48',
        r'-\sin 28',
      ],
      'answer': r'-\cos 28',
      'coins': 6,
      'xp': 25,
      'answerBuyCoins': 10,
    },
    'question9': {
      'question': {
        'firstLine': r'\mathbf{A=\frac {2\bm{\pi}} 3}',
        'secondLine': [
          'නම්',
          r'\mathbf{\cos A - \sin A}',
          'හි',
        ],
        'thirdLine': 'අගය පහතින් කුමක්ද?',
      },
      'answers': [
        r'\frac {1 + \sqrt 3} 2',
        r'\frac {1 - \sqrt 3} 2',
        r'-\frac {1 + \sqrt 3} 2',
        r'1 + \sqrt 3',
        r'-\frac {\sqrt 3 - 1} 2',
      ],
      'answer': r'-\frac {1 + \sqrt 3} 2',
      'coins': 7,
      'xp': 28,
      'answerBuyCoins': 12,
    },
    'question10': {
      'question': {
        'firstLine': r'\mathbf{\bm{\theta}=\frac {7\bm{\pi}} 4}',
        'secondLine': [
          'නම්',
          r'\mathbf{\tan\bm{\theta} + \cot\bm{\theta}}',
          'හි',
        ],
        'thirdLine': 'අගය පහතින් තෝරන්න.',
      },
      'answers': [
        r'0',
        r'2',
        r'\frac 2 {\sqrt 3}',
        r'-2',
        r'-2\sqrt 3',
      ],
      'answer': r'-2',
      'coins': 7,
      'xp': 28,
      'answerBuyCoins': 12,
    },
    'question11': {
      'question': {
        'firstLine': r'\mathbf{\cot A + \tan (180 + A) + \tan (90 + A) + \tan (360 - A)}',
        'thirdLine': 'සමාන වනුයේ පහතින් කුමකටද?',
      },
      'answers': [
        r'2(\tan A + \cot A)',
        r'2\cot A',
        r'3\tan A',
        r'\tan A + \cot A',
        r'0',
      ],
      'answer': r'0',
      'coins': 8,
      'xp': 30,
      'answerBuyCoins': 12,
    },
    'question12': {
      'question': {
        'firstLine': r'\mathbf{A=278}',
        'secondLine': [
          'නම්',
          r'\mathbf{\sin A + \cos A}',
          'හි',
        ],
        'thirdLine': 'ලකුණ කුමක්ද?',
      },
      'answers': [
        r'-',
        r'+',
      ],
      'answer': r'-',
      'coins': 9,
      'xp': 35,
      'answerBuyCoins': 14,
    },
    'question13': {
      'question': {
        'firstLine': r'\mathbf{A=215}',
        'secondLine': [
          'නම්',
          r'\mathbf{\sin A - \cos A}',
          'හි',
        ],
        'thirdLine': 'ලකුණ කුමක්ද?',
      },
      'answers': [
        r'-',
        r'+',
      ],
      'answer': r'-',
      'coins': 9,
      'xp': 35,
      'answerBuyCoins': 14,
    },
    'question14': {
      'question': {
        'firstLine': r'\mathbf{A=-356}',
        'secondLine': [
          'නම්',
          r'\mathbf{\sin A + \cos A}',
          'හි',
        ],
        'thirdLine': 'ලකුණ වනුයේ?',
      },
      'answers': [
        r'-',
        r'+',
      ],
      'answer': r'+',
      'coins': 11,
      'xp': 40,
      'answerBuyCoins': 17,
    },
    'question15': {
      'question': {
        'firstLine': r'\mathbf{A=-634}',
        'secondLine': [
          'නම්',
          r'\mathbf{\cos A - \sin A}',
          'හි',
        ],
        'thirdLine': 'ලකුණ සොයන්න.',
      },
      'answers': [
        r'-',
        r'+',
      ],
      'answer': r'-',
      'coins': 13,
      'xp': 45,
      'answerBuyCoins': 20,
    },
  },
  'stage4': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\sin 75 - \sin 15}',
        'thirdLine': 'මෙම ප්‍රකාශයේ අගය සොයන්න.',
      },
      'answers': [
        r'\frac 1 {\sqrt 2}',
        r'\frac 1 {2\sqrt 2}',
        r'\frac {{\sqrt 3} - 1} 2',
        r'\frac {{\sqrt 3} - 1} {\sqrt 2}',
        r'0',
      ],
      'answer': r'\frac 1 {\sqrt 2}',
      'coins': 5,
      'xp': 25,
      'answerBuyCoins': (5*2.1).ceil(),
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{\cos(45 - A)\cos(45 - B) - \sin(45 - A)\sin(45 - B)}',
        'thirdLine': 'මෙම ප්‍රකාශය පහත කුමන ප්‍රකාශයට සමාන වේද?',
      },
      'answers': [
        r'\frac 2 {\sqrt 2}',
        r'\cos(A + B)',
        r'\sin(A + B)',
        r'\sin(A - B)',
        r'\cos(A - B)',
      ],
      'answer': r'\sin(A + B)',
      'coins': 6,
      'xp': 28,
      'answerBuyCoins': (6*2.1).ceil(),
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{\sin(45 + A)\cos(45 - B) + \cos(45 + A)\sin(45 - B)}',
        'thirdLine': 'මෙම ප්‍රකාශය පහත කුමන ප්‍රකාශයට සමාන වේද?',
      },
      'answers': [
        r'\frac 2 {\sqrt 2}',
        r'\cos(A + B)',
        r'\sin(A + B)',
        r'\sin(A - B)',
        r'\cos(A - B)',
      ],
      'answer': r'\cos(A - B)',
      'coins': 6,
      'xp': 28,
      'answerBuyCoins': (6*2.1).ceil(),
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin A + \sin 2A} {\cos A - \cos 2A}}',
        'thirdLine': 'මෙම ප්‍රකාශය පහත කුමකට සමාන වේද?',
      },
      'answers': [
        r'\cot \frac {3A} 2',
        r'\tan \frac A 2',
        r'-\cot \frac {3A} 2',
        r'\cot \frac A 2',
        r'-\tan \frac {3A} 2',
      ],
      'answer': r'\cot \frac A 2',
      'coins': 7,
      'xp': 30,
      'answerBuyCoins': (7*2.1).ceil(),
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{\sin 105 + \cos 105}',
        'thirdLine': 'සමාන වනුයේ පහත කුමන අගයකටද?',
      },
      'answers': [
        r'\frac 2 {\sqrt 2}',
        r'\frac 1 {\sqrt 2}',
        r'\frac 1 {2\sqrt 2}',
        r'\frac {{\sqrt 3} + 1} 2',
        r'\frac {{\sqrt 3} - 1} 2',
      ],
      'answer': r'\frac 1 {\sqrt 2}',
      'coins': 7,
      'xp': 32,
      'answerBuyCoins': (7*2.1).ceil(),
    },
    'question6': {
      'question': {
        'firstLine': r'\mathbf{\frac {\cos 2B - \cos 2A} {\sin 2B + \sin 2A}}',
        'thirdLine': 'මෙම ප්‍රකාශයට සමාන ප්‍රකාශය පහත ප්‍රකාශ අතුරින් තෝරන්න.',
      },
      'answers': [
        r'\tan A - \tan B',
        r'\cot(A - B)',
        r'\tan(A - B)',
        r'\tan(A + B)',
        r'\cot(A + B)',
      ],
      'answer': r'\tan(A - B)',
      'coins': 8,
      'xp': 35,
      'answerBuyCoins': (8*2.1).ceil(),
    },
    'question7': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin 7\bm{\theta} - \sin 5\bm{\theta}} {\cos 7\bm{\theta} + \cos 5\bm{\theta}}}',
        'thirdLine': 'මෙම ප්‍රකාශයට සමාන ප්‍රකාශය පහත ප්‍රකාශ අතුරින් තෝරන්න.',
      },
      'answers': [
        r'\tan\theta',
        r'\tan 2\theta',
        r'\cot\theta',
        r'\cot 2\theta',
        r'\frac {\sin 3\theta} {\cos 6\theta}',
      ],
      'answer': r'\tan\theta',
      'coins': 8,
      'xp': 35,
      'answerBuyCoins': (8*2.1).ceil(),
    },
    'question8': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin 7A - \sin A} {\sin 8A - \sin 2A}}',
        'thirdLine': 'මෙම ප්‍රකාශයට සමාන ප්‍රකාශය පහතින් තෝරන්න.',
      },
      'answers': [
        r'\frac {\cos 4A} {\sin 5A}',
        r'\frac {\cos 5A} {\sin 4A}',
        r'\cos 5A\cos 4A',
        r'\cos 5A\sec 4A',
        r'\cos 4A\sec 5A',
      ],
      'answer': r'\cos 4A\sec 5A',
      'coins': 8,
      'xp': 35,
      'answerBuyCoins': (8*2.1).ceil(),
    },
    'question9': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin A + \sin B} {\cos A + \cos B}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමකටද?',
      },
      'answers': [
        r'\tan(A + B)',
        r'\cot(A + B)',
        r'\cot\bigg(\frac {A + B} 2\bigg)',
        r'\tan\bigg(\frac {A + B} 2\bigg)',
        r'\tan(A - B)',
      ],
      'answer': r'\tan\bigg(\frac {A + B} 2\bigg)',
      'coins': 9,
      'xp': 37,
      'answerBuyCoins': (9*2.1).ceil(),
    },
    'question10': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin A + \sin B} {\sin A - \sin B}}',
        'thirdLine': 'මෙම ප්‍රකාශයට සමාන වනුයේ පහතින් කුමක්ද?',
      },
      'answers': [
        r'\tan\bigg(\frac {A + B} 2\bigg)',
        r'\tan\bigg(\frac {A + B} 2\bigg) \cot\bigg(\frac {A - B} 2\bigg)',
        r'\tan\bigg(\frac {A - B} 2\bigg) \cot\bigg(\frac {A + B} 2\bigg)',
        r'\tan (A - B)\cot (A + B)',
        r'\cot\bigg(\frac {A + B} 2\bigg)',
      ],
      'answer': r'\tan\bigg(\frac {A + B} 2\bigg) \cot\bigg(\frac {A - B} 2\bigg)',
      'coins': 9,
      'xp': 40,
      'answerBuyCoins': (9*2.1).ceil(),
    },
    'question11': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin(4A - 2B) + \sin(4B - 2A)} {\cos(4A - 2B) + \cos(4B - 2A)}}',
        'thirdLine': 'මෙම ප්‍රකාශයට සමාන වනුයේ පහතින් කුමක්ද?',
      },
      'answers': [
        r'\tan(A + B)',
        r'\tan A + \tan B',
        r'\tan(A - B)',
        r'\cot(A + B)',
        r'\cot(A - B)',
      ],
      'answer': r'\tan(A + B)',
      'coins': 9,
      'xp': 40,
      'answerBuyCoins': (9*2.1).ceil(),
    },
    'question12': {
      'question': {
        'firstLine': r'\mathbf{\sin\bm{\alpha} = \frac 3 5,\cos\bm{\beta} = \frac 9 {41}}',
        'secondLine': [
          'නම්',
          r'\mathbf{\sin(\bm{\alpha} - \bm{\beta})}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
        'forthLine': r'\Big(0<\alpha,\beta<\frac \pi 2\Big)',
      },
      'answers': [
        r'\frac {187} {205}',
        r'-\frac {133} {205}',
        r'\frac {27-4\sqrt{1529}} {205}',
        r'\frac {27} {205}',
        r'\frac {160} {205}',
      ],
      'answer': r'-\frac {133} {205}',
      'coins': 10,
      'xp': 43,
      'answerBuyCoins': (10*2.1).ceil(),
    },
    'question13': {
      'question': {
        'firstLine': r'\mathbf{\sin\bm{\alpha} = \frac {45} {53},\sin\bm{\beta} = \frac {33} {65}}',
        'secondLine': [
          'නම්',
          r'\mathbf{\sin(\bm{\alpha} + \bm{\beta})}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
        'forthLine': r'\Big(0<\alpha,\beta<\frac \pi 2\Big)',
      },
      'answers': [
        r'1',
        r'\frac {2520} {3445}',
        r'\frac {3424} {3445}',
        r'\frac {3444} {3445}',
        r'\frac {3442} {3445}',
      ],
      'answer': r'\frac {3444} {3445}',
      'coins': 10,
      'xp': 43,
      'answerBuyCoins': (10*2.1).ceil(),
    },
    'question14': {
      'question': {
        'firstLine': r'\mathbf{\tan A = \frac 1 2,\tan B = \frac 1 3}',
        'secondLine': [
          'නම්',
          r'\mathbf{\tan(2A + B)}',
          'හි',
        ],
        'thirdLine': 'අගය පහතින් තෝරන්න.',
      },
      'answers': [
        r'3',
        r'\frac 5 6',
        r'\frac 6 5',
        r'\frac 5 3',
        r'\frac 1 3',
      ],
      'answer': r'3',
      'coins': 10,
      'xp': 43,
      'answerBuyCoins': (10*2.1).ceil(),
    },
    'question15': {
      'question': {
        'firstLine': r'\mathbf{\sin 50 - \sin 70 + \sin 10}',
        'thirdLine': 'මෙහි අගය පහතින් තෝරන්න.',
      },
      'answers': [
        r'1',
        r'2\sin 70',
        r'-2\sin 70',
        r'\cos 20',
        r'0',
      ],
      'answer': r'0',
      'coins': 11,
      'xp': 46,
      'answerBuyCoins': (11*2.1).ceil(),
    },
    'question16': {
      'question': {
        'firstLine': r'\mathbf{\tan (45 + \bm{\theta})\tan (135 + \bm{\theta})}',
        'thirdLine': 'මෙහි අගය පහතින් තෝරන්න.',
      },
      'answers': [
        r'1',
        r'0',
        r'-1',
        r'2',
        r'-2',
      ],
      'answer': r'-1',
      'coins': 11,
      'xp': 46,
      'answerBuyCoins': (11*2.1).ceil(),
    },
    'question17': {
      'question': {
        'firstLine': r'\mathbf{\frac {\tan 5A + \tan 3A} {\tan 5A - \tan 3A}}',
        'thirdLine': 'මෙම ප්‍රකාශයට සමාන ප්‍රකාශය තෝරන්න.',
      },
      'answers': [
        r'4\cos A\cos 4A',
        r'\frac {\tan 4A} {\tan A}',
        r'4\cos 2A\cos 4A',
        r'2\cos 2A\cos 4A',
        r'2\cos^2 2A',
      ],
      'answer': r'4\cos 2A\cos 4A',
      'coins': 13,
      'xp': 48,
      'answerBuyCoins': (13*2.1).ceil(),
    },
    'question18': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin(A + B) - 2\sin A + \sin(A - B)} {\cos(A + B) - 2\cos A + \cos(A - B)}}',
        'thirdLine': 'මෙම ප්‍රකාශය පහත කුමකට සමාන වේද?',
      },
      'answers': [
        r'2\cos A\cos B',
        r'\cot A\tan B',
        r'\tan B\cos A',
        r'\tan A',
        r'\cot B\sin A',
      ],
      'answer': r'\tan A',
      'coins': 13,
      'xp': 52,
      'answerBuyCoins': (13*2.1).ceil(),
    },
    'question19': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin A + \sin 3A + \sin 5A + \sin 7A} {\cos A + \cos 3A + \cos 5A + \cos 7A}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\cot 4A',
        r'\frac {\cos 3A - cos A} {\cos 3A + cos A}',
        r'-\cot 2A',
        r'-\tan 2A',
        r'\tan 4A',
      ],
      'answer': r'\tan 4A',
      'coins': 15,
      'xp': 57,
      'answerBuyCoins': (15*2.1).ceil(),
    },
    'question20': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin A - \sin 5A + \sin 9A - \sin 13A} {\cos A - \cos 5A - \cos 9A + \cos 13A}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\cot 4A',
        r'\frac {\cos 3A - cos A} {\cos 3A + cos A}',
        r'-\cot 2A',
        r'-\tan 2A',
        r'\tan 4A',
      ],
      'answer': r'\cot 4A',
      'coins': 15,
      'xp': 57,
      'answerBuyCoins': (15*2.1).ceil(),
    },
  },
  'stage5': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin 2\bm{\alpha}} {1 - \cos 2\bm{\alpha}}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\sec\alpha - \tan\alpha',
        r'\tan\alpha',
        r'\cosec\alpha - \cot\alpha',
        r'\cot\alpha',
        r'-\tan\alpha',
      ],
      'answer': r'\cot\alpha',
      'coins': 6,
      'xp': 32,
      'answerBuyCoins': (6*2.6).ceil(),
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{\frac {1 - \cos 2\bm{\alpha}} {1 + \cos 2\bm{\alpha}}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\cot^2\alpha',
        r'\tan^2\alpha',
        r'\cot\alpha',
        r'\frac {1 + \sin^2\alpha} {1 + \cos^2\alpha}',
        r'\cot 2\alpha',
      ],
      'answer': r'\tan^2\alpha',
      'coins': 7,
      'xp': 34,
      'answerBuyCoins': (7*2.6).ceil(),
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{\cos\bm{\alpha} = \frac 3 5}',
        'secondLine': [
          'නම්',
          r'\mathbf{\sin 2\bm{\alpha}}',
          'හි',
        ],
        'thirdLine': 'අගය කුමක්ද?',
        'forthLine': r'(0<\alpha<\pi)'
      },
      'answers': [
        r'\frac 4 5',
        r'\frac {24} {25}',
        r'\frac {12} {25}',
        r'\frac {16} {25}',
        r'1',
      ],
      'answer': r'\frac {24} {25}',
      'coins': 8,
      'xp': 37,
      'answerBuyCoins': (8*2.6).ceil(),
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{\cosec 2A + \cot 2A}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\cot^2 A',
        r'\tan^2 A',
        r'\cot A',
        r'\frac {1 + \sin^2 A} {1 + \cos^2 A}',
        r'\cot 2A',
      ],
      'answer': r'\cot A',
      'coins': 9,
      'xp': 40,
      'answerBuyCoins': (9*2.6).ceil(),
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{\tan\bm{\alpha} = \frac 5 {12}}',
        'secondLine': [
          'නම්',
          r'\mathbf{\cos 2\bm{\alpha}}',
          'හි',
        ],
        'thirdLine': 'අගය පහතින් කුමක්ද?',
      },
      'answers': [
        r'\frac {119} {144}',
        r'\frac {144} {169}',
        r'1',
        r'\frac {12} {13}',
        r'\frac {119} {169}',
      ],
      'answer': r'\frac {119} {169}',
      'coins': 11,
      'xp': 43,
      'answerBuyCoins': (11*2.6).ceil(),
    },
    'question6': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin\bm\theta + \sin 2\bm\theta} {1 + \cos\bm\theta + \cos 2\bm\theta}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\tan\theta',
        r'\frac {1 - 2\cos\theta} {1 + 2\cos\theta}',
        r'\cot\theta',
        r'\frac {1 - 2\sin\theta} {1 + 2\sin\theta}',
        r'1',
      ],
      'answer': r'\tan\theta',
      'coins': 13,
      'xp': 46,
      'answerBuyCoins': (13*2.6).ceil(),
    },
    'question7': {
      'question': {
        'firstLine': r'\mathbf{\frac {2\tan\frac A 2} {1 + \tan^2\frac A 2}}',
        'thirdLine': 'මෙම ප්‍රකාශය පහත ප්‍රකාශ අතුරින් කුමකට සමාන වේද?',
      },
      'answers': [
        r'\tan A',
        r'\cos A',
        r'\sec A',
        r'\sin A',
        r'\cot A',
      ],
      'answer': r'\sin A',
      'coins': 15,
      'xp': 48,
      'answerBuyCoins': (15*2.6).ceil(),
    },
    'question8': {
      'question': {
        'firstLine': r'\mathbf{\frac {\cos A + \sin A} {\cos A - \sin A} - \frac {\cos A - \sin A} {\cos A + \sin A}}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත ප්‍රකාශ අතුරින් කුමකටද?',
      },
      'answers': [
        r'2\tan 2A',
        r'\cot 2A',
        r'2tan A',
        r'\tan 2A',
        r'\frac {\cot 2A} 2',
      ],
      'answer': r'2\tan 2A',
      'coins': 16,
      'xp': 55,
      'answerBuyCoins': (16*2.6).ceil(),
    },
    'question9': {
      'question': {
        'firstLine': r'\mathbf{\frac {\sin (A + 3B) + \sin (3A + B)} {\sin 2A + \sin 2B}}',
        'thirdLine': 'මෙය පහත කුමකට සමාන වේද?',
      },
      'answers': [
        r'\cos 2(A + B)',
        r'\cos 2(A - B)',
        r'2\cos (A - B)',
        r'\cos (A + B)',
        r'2\cos (A + B)',
      ],
      'answer': r'2\cos (A + B)',
      'coins': 17,
      'xp': 55,
      'answerBuyCoins': (17*2.6).ceil(),
    },
    'question10': {
      'question': {
        'firstLine': r'\mathbf{\cot (A + 15) - \tan (A - 15)}',
        'thirdLine': 'යන ප්‍රකාශය පහත ප්‍රකාශ අතුරින් කුමකට සමාන වේද?',
      },
      'answers': [
        r'\frac {\cos 2A} {1 + 2\sin 2A}',
        r'\frac {2\cos 2A} {1 + 2\sin 2A}',
        r'\frac {4\cos 2A} {1 + 2\sin 2A}',
        r'\frac {2\cos 2A} {1 - 2\sin 2A}',
        r'\frac {4\cos 2A} {1 - 2\sin 2A}',
      ],
      'answer': r'\frac {4\cos 2A} {1 + 2\sin 2A}',
      'coins': 18,
      'xp': 60,
      'answerBuyCoins': (18*2.6).ceil(),
    },
  },
  'stage6': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\cos 3A}',
        'thirdLine': 'සුත්‍රය පහත සූත්‍ර අතුරින් කුමක්ද?',
      },
      'answers': [
        r'3\cos^3 A - 4\cos A',
        r'3\cos A - 4\cos^3 A',
        r'4\cos^3 A - 3\cos A',
        r'4\cos A - 3\cos^3 A',
        r'3\cos^3 A + 4\cos A',
      ],
      'answer': r'4\cos^3 A - 3\cos A',
      'coins': 12,
      'xp': 40,
      'answerBuyCoins': (12*2.6).ceil(),
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{\tan 3A}',
        'thirdLine': 'සුත්‍රය කුමක්ද?',
      },
      'answers': [
        r'\frac {3\tan A - 4\tan^3 A} {1 - 3\tan^2 A}',
        r'\frac {3\tan A - 4\tan^2 A} {1 - 3\tan^3 A}',
        r'\frac {3\tan A - \tan^3 A} {1 - 3\tan^3 A}',
        r'\frac {4\tan A - 3\tan^3 A} {1 - 3\tan^3 A}',
        r'\frac {3\tan A - \tan^3 A} {1 - 3\tan^2 A}',
      ],
      'answer': r'\frac {3\tan A - \tan^3 A} {1 - 3\tan^2 A}',
      'coins': 15,
      'xp': 55,
      'answerBuyCoins': (15*2.6).ceil(),
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{\cos 6\bm\alpha}',
        'thirdLine': 'සමාන වනුයේ පහත කුමන ප්‍රකාශනයටද?',
      },
      'answers': [
        r'32\cos^6\alpha + 48\cos^4\alpha + 18\cos^2\alpha + 1',
        r'32\cos^6\alpha - 48\cos^4\alpha + 18\cos^2\alpha - 1',
        r'2\cos^3 3\alpha + 1',
        r'32\cos^6\alpha - 48\cos^4\alpha + 18\cos^2\alpha + 1',
        r'1 - 32\cos^6\alpha + 48\cos^4\alpha - 18\cos^2\alpha',
      ],
      'answer': r'32\cos^6\alpha - 48\cos^4\alpha + 18\cos^2\alpha - 1',
      'coins': 19,
      'xp': 75,
      'answerBuyCoins': (19*2.6).ceil(),
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{\sin\bm\alpha\sin(60 - \bm\alpha)\sin(60 + \bm\alpha)}',
        'thirdLine': 'සමාන වනුයේ පහත කුමන ප්‍රකාශනයටද?',
      },
      'answers': [
        r'\frac {\sqrt 3} 2 \sin 2\alpha',
        r'\frac 1 4 \cos 2\alpha',
        r'\frac 1 4 \sin 3\alpha',
        r'\frac {\sqrt 3} 2 \cos 3\alpha',
        r'\frac 1 4 \sin 2\alpha',
      ],
      'answer': r'\frac 1 4 \sin 3\alpha',
      'coins': 24,
      'xp': 100,
      'answerBuyCoins': (24*2.6).ceil(),
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{\cot\bm\alpha + \cot(60 + \bm\alpha) - \cot(60 - \bm\alpha)}',
        'thirdLine': 'සමාන වනුයේ පහත කුමන ප්‍රකාශනයටද?',
      },
      'answers': [
        r'\tan 3\alpha',
        r'\cot 3\alpha',
        r'\sqrt 3\tan 3\alpha',
        r'3\cot 3\alpha',
        r'\frac 1 {\sqrt 3} \tan 3\alpha',
      ],
      'answer': r'3\cot 3\alpha',
      'coins': 30,
      'xp': 130,
      'answerBuyCoins': (30*2.6).ceil(),
    },
  },
  'stage7': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\sin 3\bm\theta = \sin 2\bm\theta}',
        'thirdLine': 'සමීකරණයේ සාධාරන විසඳුම් හෝ විසඳුම සොයන්න.',
      },
      'answers': [
        r'\frac {(2n \pm 1)\pi} 5 \text{  }or\text{  } 2n\pi',
        r'\frac {(4n \pm 1)\pi} 5 \text{  }or\text{  } 2n\pi',
        r'\frac {(n \pm 1)\pi} 5 \text{  }or\text{  } n\pi',
        r'\frac {(2n \pm 1)\pi} {10} \text{  }or\text{  } \frac {n\pi} 2',
        r'\frac {(3n \pm 1)\pi} 5 \text{  }or\text{  } \frac {3n\pi} 2',
      ],
      'answer': r'\frac {(4n \pm 1)\pi} 5 \text{  }or\text{  } 2n\pi',
      'coins': 17,
      'xp': 80,
      'answerBuyCoins': (17*2.6).ceil(),
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{\tan 2\bm\theta\tan\bm\theta = 1}',
        'thirdLine': 'සමීකරණයේ සාධාරන විසඳුම් හෝ විසඳුම පහතින් තෝරන්න.',
      },
      'answers': [
        r'\bigg(n\pi + \frac {\pi} 3\bigg) \text{  }or\text{  } \bigg(n\pi + \frac {2\pi} 3\bigg)',
        r'\bigg(2n\pi + \frac {\pi} 6\bigg) \text{  }or\text{  } \bigg(n\pi + \frac {5\pi} 6\bigg)',
        r'\bigg(n\pi + \frac {\pi} 6\bigg) \text{  }or\text{  } \bigg(\frac {2n\pi} 3 + \frac {2\pi} 3\bigg)',
        r'2n\pi \text{  }or\text{  } \bigg(n\pi + \frac {\pi} 6\bigg)',
        r'\bigg(n\pi + \frac {\pi} 6\bigg) \text{  }or\text{  } \bigg(n\pi + \frac {5\pi} 6\bigg)',
      ],
      'answer': r'\bigg(n\pi + \frac {\pi} 6\bigg) \text{  }or\text{  } \bigg(n\pi + \frac {5\pi} 6\bigg)',
      'coins': 20,
      'xp': 85,
      'answerBuyCoins': (20*2.6).ceil(),
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{\cos^2 \bm\theta - \sin\bm\theta - \frac 1 4 = 0}',
        'thirdLine': 'සමීකරණයේ සාධාරන විසඳුම් හෝ විසඳුම කුමක්ද?',
      },
      'answers': [
        r'n\pi + (-1)^n\Big(\frac {\pi} 6\Big)',
        r'2n\pi \pm \frac {\pi} 3',
        r'n\pi + (-1)^n\Big(\frac {-\pi} 6\Big)',
        r'2n\pi \pm \frac {-\pi} 3',
        r'2n\pi \pm \frac {\pi} 6',
      ],
      'answer': r'n\pi + (-1)^n\Big(\frac {\pi} 6\Big)',
      'coins': 23,
      'xp': 90,
      'answerBuyCoins': (23*2.6).ceil(),
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{3\sin^2 \bm\theta - 2\sin\bm\theta = 1}',
        'thirdLine': 'සමීකරණයේ සාධාරන විසඳුම් හෝ විසඳුම කුමක්ද?',
      },
      'answers': [
        r'\bigg(n\pi + (-1)^n\Big(\frac {-\pi} 2\Big)\bigg) \text{  }or\text{  } \bigg(n\pi + (-1)^n\sin^{-1}\Big(\frac 1 3\Big)\bigg)',
        r'\bigg(n\pi + (-1)^n\Big(\frac {\pi} 4\Big)\bigg) \text{  }or\text{  } \bigg(n\pi + (-1)^n\sin^{-1}\Big(-\frac 1 3\Big)\bigg)',
        r'\bigg(\frac {n\pi} 2 + (-1)^n\Big(\frac {\pi} 4\Big)\bigg) \text{  }or\text{  } \bigg(n\pi + (-1)^n\Big(\frac {\pi} 6\Big)\bigg)',
        r'\bigg(n\pi + (-1)^n\sin^{-1}\Big(\frac 1 4\Big)\bigg) \text{  }or\text{  } \bigg(n\pi + (-1)^n\sin^{-1}\Big(\frac 1 3\Big)\bigg)',
        r'\bigg(n\pi + (-1)^n\Big(\frac {\pi} 2\Big)\bigg) \text{  }or\text{  } \bigg(n\pi + (-1)^n\sin^{-1}\Big(-\frac 1 3\Big)\bigg)',
      ],
      'answer': r'\bigg(n\pi + (-1)^n\Big(\frac {\pi} 2\Big)\bigg) \text{  }or\text{  } \bigg(n\pi + (-1)^n\sin^{-1}\Big(-\frac 1 3\Big)\bigg)',
      'coins': 28,
      'xp': 95,
      'answerBuyCoins': (28*2.6).ceil(),
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{\cos(m\bm\theta) = \cos(n\bm\theta)}',
        'thirdLine': 'සමීකරණයේ සාධාරන විසඳුම් හෝ විසඳුම කුමක්ද?',
      },
      'answers': [
        r'\bigg(\frac {n\pi} {m + n}\bigg) \text{  }or\text{  } \bigg(\frac {n\pi} {m - n}\bigg)',
        r'\bigg(\frac {2n\pi} {m - n}\bigg) \text{  }or\text{  } \bigg(\frac {n\pi} {m + n}\bigg)',
        r'\bigg(\frac {2n\pi} {m - n}\bigg) \text{  }or\text{  } \bigg(\frac {2n\pi} {m + n}\bigg)',
        r'\bigg(\frac {n\pi} {n - m}\bigg) \text{  }or\text{  } \bigg(\frac {n\pi} {m + n}\bigg)',
        r'\bigg(\frac {2n\pi} {n - m}\bigg) \text{  }or\text{  } \bigg(\frac {n\pi} {m + n}\bigg)',
      ],
      'answer': r'\bigg(\frac {2n\pi} {m - n}\bigg) \text{  }or\text{  } \bigg(\frac {2n\pi} {m + n}\bigg)',
      'coins': 32,
      'xp': 100,
      'answerBuyCoins': (32*2.6).ceil(),
    },
  },
  'stage8': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\sin^{-1} \Big(\frac 3 5\Big) + \sin^{-1} \Big(\frac 8 {17}\Big)}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන අගයකටද?',
      },
      'answers': [
        r'\sin^{-1} \Big(\frac {13} {85}\Big)',
        r'\cos^{-1} \Big(\frac {77} {85}\Big)',
        r'\sin^{-1} \Big(\frac {77} {85}\Big)',
        r'\cos^{-1} \Big(\frac {13} {85}\Big)',
        r'\frac \pi 6',
      ],
      'answer': r'\sin^{-1} \Big(\frac {77} {85}\Big)',
      'coins': 12,
      'xp': 40,
      'answerBuyCoins': (12*2.4).ceil(),
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{\cos^{-1} \Big(\frac 4 5\Big) + \cos^{-1} \Big(\frac {12} {13}\Big)}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන අගයකටද?',
      },
      'answers': [
        r'\cos^{-1} \Big(\frac {33} {65}\Big)',
        r'\frac \pi 3',
        r'\sin^{-1} \Big(\frac {63} {65}\Big)',
        r'\sin^{-1} \Big(\frac {33} {65}\Big)',
        r'\cos^{-1} \Big(\frac {63} {65}\Big)',
      ],
      'answer': r'\cos^{-1} \Big(\frac {33} {65}\Big)',
      'coins': 12,
      'xp': 40,
      'answerBuyCoins': (12*2.4).ceil(),
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{\cos^{-1} \Big(\frac 4 5\Big) + \tan^{-1} \Big(\frac 3 5\Big)}',
        'thirdLine': 'මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන අගයකටද?',
      },
      'answers': [
        r'\frac \pi 4',
        r'\tan^{-1} \Big(\frac {27} {11}\Big)',
        r'\tan^{-1} \Big(\frac {11} {27}\Big)',
        r'\tan^{-1} \Big(\frac 3 {29}\Big)',
        r'\tan^{-1} \Big(\frac {29} 3\Big)',
      ],
      'answer': r'\tan^{-1} \Big(\frac {27} {11}\Big)',
      'coins': 16,
      'xp': 55,
      'answerBuyCoins': (16*2.4).ceil(),
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{\tan^{-1} \Big(\frac 3 4\Big) + \tan^{-1} \Big(\frac 3 5\Big) - \tan^{-1} \Big(\frac 9 {19}\Big)}',
        'thirdLine': 'අගය කුමක්ද?',
      },
      'answers': [
        r'\tan^{-1} \Big(\frac {27} {11}\Big)',
        r'\frac \pi 4',
        r'\tan^{-1} \Big(\frac {601} {425}\Big)',
        r'\tan^{-1} \Big(\frac {425} {601}\Big)',
        r'0',
      ],
      'answer': r'\frac \pi 4',
      'coins': 20,
      'xp': 70,
      'answerBuyCoins': (20*2.4).ceil(),
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{\frac {\bm\pi} 4 - \tan^{-1} \Big(\frac 1 {1985}\Big)}',
        'thirdLine': 'අගය කුමක්ද?',
      },
      'answers': [
        r'0',
        r'\tan^{-1} \Big(\frac {1984} {1985}\Big)',
        r'\tan^{-1} \Big(\frac {1985} {1984}\Big)',
        r'\tan^{-1} \Big(\frac {1985} {1986}\Big)',
        r'\tan^{-1} \Big(\frac {1984} {1986}\Big)',
      ],
      'answer': r'\tan^{-1} \Big(\frac {1984} {1986}\Big)',
      'coins': 22,
      'xp': 75,
      'answerBuyCoins': (22*2.4).ceil(),
    },
    'question6': {
      'question': {
        'firstLine': r'\mathbf{4\tan^{-1} \Big(\frac 1 5\Big) - \tan^{-1} \Big(\frac 1 {70}\Big) + \tan^{-1} \Big(\frac 1 {99}\Big)}',
        'thirdLine': 'අගය කුමක්ද?',
      },
      'answers': [
        r'\tan^{-1} \Big(\frac {-29} {6931}\Big)',
        r'0',
        r'\tan^{-1} \Big(\frac {120} {119}\Big)',
        r'\frac \pi 4',
        r'\tan^{-1} \Big(\frac {29} {6931}\Big)',
      ],
      'answer': r'\frac \pi 4',
      'coins': 27,
      'xp': 100,
      'answerBuyCoins': (27*2.4).ceil(),
    },
    'question7': {
      'question': {
        'firstLine': r'\mathbf{\tan^{-1} \Big(\frac {x - 1} {x - 2}\Big) + \tan^{-1} \Big(\frac {x + 1} {x + 2}\Big) = \frac \pi 4}',
        'thirdLine': 'අගය කුමක්ද?',
      },
      'answers': [
        r'x = \frac 1 2 \text{  }or\text{  } x = -\frac 1 2',
        r'x = -1 \text{  }or\text{  } x = \frac 1 2',
        r'x = -\frac 1 {\sqrt 2} \text{  }or\text{  } x = \frac 1 {\sqrt 2}',
        r'x = \frac 1 2 \text{  }or\text{  } x = \frac 2 3',
        r'x = \frac 1 {\sqrt 2} \text{  }or\text{  } x = \frac 1 2',
      ],
      'answer': r'x = -\frac 1 {\sqrt 2} \text{  }or\text{  } x = \frac 1 {\sqrt 2}',
      'coins': 27,
      'xp': 100,
      'answerBuyCoins': (27*2.4).ceil(),
    },
    'question8': {
      'question': {
        'firstLine': r'\mathbf{\tan^{-1} (x + 1) + \tan^{-1} (x - 1) = \tan^{-1} \Big(\frac 8 {31}\Big)}',
        'secondLine': [
          'නම්',
          r'\mathbf{x}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
      },
      'answers': [
        r'x = 1 \text{  }or\text{  } x = -1',
        r'x = \frac 1 4 \text{  }or\text{  } x = -8',
        r'x = \frac 1 2 \text{  }or\text{  } x = -4',
        r'x = 4 \text{  }or\text{  } x = -\frac 1 8',
        r'x = \frac 1 2 \text{  }or\text{  } x = -\frac 1 2',
      ],
      'answer': r'x = \frac 1 4 \text{  }or\text{  } x = -8',
      'coins': 30,
      'xp': 110,
      'answerBuyCoins': (30*2.4).ceil(),
    },
    'question9': {
      'question': {
        'firstLine': r'\mathbf{\cot^{-1} x - \cot^{-1} (x + 2) = 15^o}',
        'secondLine': [
          'නම්',
          r'\mathbf{x}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
      },
      'answers': [
        r'\bigg(x = \Big(\frac {\sqrt 3 - 3} {\sqrt 3 - 1}\Big)\bigg) \text{  }or\text{  } \bigg(x = \Big(\frac {\sqrt 3 + 1} {\sqrt 3 - 1}\Big)\bigg)',
        r'\bigg(x = \Big(\frac {3 - \sqrt 3} {\sqrt 3 - 1}\Big)\bigg) \text{  }or\text{  } \bigg(x = \Big(\frac {\sqrt 3 + 1} {\sqrt 3 - 1}\Big)\bigg)',
        r'\bigg(x = \Big(\frac {\sqrt 3 - 3} {\sqrt 3 + 1}\Big)\bigg) \text{  }or\text{  } \bigg(x = \Big(\frac {\sqrt 3 + 1} {\sqrt 3 - 1}\Big)\bigg)',
        r'\bigg(x = \Big(\frac {\sqrt 3 - 3} {\sqrt 3 - 1}\Big)\bigg) \text{  }or\text{  } \bigg(x = \Big(\frac {\sqrt 3 - 1} {\sqrt 3 + 1}\Big)\bigg)',
        r'\bigg(x = \Big(\frac {\sqrt 3 - 1} {\sqrt 3 - 3}\Big)\bigg) \text{  }or\text{  } \bigg(x = \Big(\frac {\sqrt 3 + 1} {\sqrt 3 - 1}\Big)\bigg)',
      ],
      'answer': r'\bigg(x = \Big(\frac {\sqrt 3 - 3} {\sqrt 3 - 1}\Big)\bigg) \text{  }or\text{  } \bigg(x = \Big(\frac {\sqrt 3 + 1} {\sqrt 3 - 1}\Big)\bigg)',
      'coins': 34,
      'xp': 125,
      'answerBuyCoins': (34*2.4).ceil(),
    },
    'question10': {
      'question': {
        'firstLine': r'\mathbf{\tan [\cos^{-1} x] = \sin\bigg[\cot^{-1} \Big(\frac 1 2\Big)\bigg]}',
        'secondLine': [
          'නම්',
          r'\mathbf{x}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
      },
      'answers': [
        r'x = \frac {\sqrt 2} 3 \text{  }or\text{  } x = -\frac {\sqrt 2} 3',
        r'x = \frac {\sqrt 5} {\sqrt 3} \text{  }or\text{  } x = -\frac {\sqrt 5} 3',
        r'x = \frac 5 {\sqrt 3} \text{  }or\text{  } x = -\frac 5 {\sqrt 3}',
        r'x = \frac 5 9 \text{  }or\text{  } x = -\frac 5 9',
        r'x = \frac {\sqrt 5} 3 \text{  }or\text{  } x = -\frac {\sqrt 5} 3',
      ],
      'answer': r'x = \frac {\sqrt 5} 3 \text{  }or\text{  } x = -\frac {\sqrt 5} 3',
      'coins': 40,
      'xp': 135,
      'answerBuyCoins': (40*2.4).ceil(),
    },
  },
  'stage9': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{y = 3 + 4\cos\Big(\frac {2x} 3\Big)}',
        'thirdLine': 'මෙම ප්‍රස්තාරයේ උපරිමය සහ තරංග ආයාමය සොයන්න.',
      },
      'answers': [
        r'y_{max} = 3 \text{  }and\text{  } \lambda = 4\pi',
        r'y_{max} = 7 \text{  }and\text{  } \lambda = 4\pi',
        r'y_{max} = 3 \text{  }and\text{  } \lambda = \frac {3\pi} 2',
        r'y_{max} = 7 \text{  }and\text{  } \lambda = 3\pi',
        r'y_{max} = 3 \text{  }and\text{  } \lambda = 2\pi',
      ],
      'answer': r'y_{max} = 7 \text{  }and\text{  } \lambda = 3\pi',
      'coins': 12,
      'xp': 40,
      'answerBuyCoins': (12*2.6).ceil(),
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{y = 1 + 2\sin\Big(\frac {x} 2\Big)}',
        'thirdLine': 'මෙහි ප්‍රස්තාරය පහතින් තෝරන්න',
      },
      'answers': [
        'S9Q2A1',
        'S9Q2A2',
        'S9Q2A3',
        'S9Q2A4',
        'S9Q2A5',
      ],
      'answer': 'S9Q2A5',
      'coins': 13,
      'xp': 45,
      'answerBuyCoins': (13*2.6).ceil(),
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{y = 3\tan\Big(\frac {x} 2\Big)}',
        'thirdLine': 'මෙහි ප්‍රස්තාරය පහතින් තෝරන්න',
      },
      'answers': [
        'S9Q3A1',
        'S9Q3A2',
        'S9Q3A3',
        'S9Q3A4',
        'S9Q3A5',
      ],
      'answer': 'S9Q3A3',
      'coins': 15,
      'xp': 45,
      'answerBuyCoins': (15*2.6).ceil(),
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{3y - 9 = \sin 3x}',
        'thirdLine': 'මෙහි ප්‍රස්තාරය පහතින් තෝරන්න',
      },
      'answers': [
        'S9Q4A1',
        'S9Q4A2',
        'S9Q4A3',
        'S9Q4A4',
        'S9Q4A5',
      ],
      'answer': 'S9Q4A1',
      'coins': 20,
      'xp': 70,
      'answerBuyCoins': (20*2.6).ceil(),
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{y = 2 + \frac 1 3 \sin 5x}',
        'secondLine': [
          'මෙම ප්‍රස්තාරය උපරිම වන',
          r'\mathbf{x}',
          'හි',
        ],
        'thirdLine': 'අගය සොයන්න.',
        'forthLine': r'\Big(0<x<\frac \pi 6\Big)',
      },
      'answers': [
        r'\frac \pi {15}',
        r'\frac \pi {20}',
        r'\frac {2\pi} {15}',
        r'\frac \pi 6',
        r'\frac \pi {10}',
      ],
      'answer': r'\frac \pi {10}',
      'coins': 30,
      'xp': 100,
      'answerBuyCoins': (30*2.6).ceil(),
    },
  },
  'stage10': {
    'question1': {
      'question': {
        'firstLine': r'\mathbf{\frac {b^2 - c^2} {a^2}}',
        'thirdLine': 'සාධාරන ත්‍රිකෝණයක සම්මත අංකනයට අනුව මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'\frac {\sin (B - C)} {\sin (A + C)}',
        r'\frac {\sin (B - C)} {\sin (B + C)}',
        r'\frac {\sin (B + C)} {2\sin (B - C)}',
        r'\frac {2\sin (B + C)} {\sin (B - C)}',
        r'\frac {\cos (B - C)} {\sin (B + C)}',
      ],
      'answer': r'\frac {\sin (B - C)} {\sin (B + C)}',
      'coins': 20,
      'xp': 80,
      'answerBuyCoins': (20*2.6).ceil(),
    },
    'question2': {
      'question': {
        'firstLine': r'\mathbf{b^2\sin 2C + c^2\sin 2B}',
        'thirdLine': 'සාධාරන ත්‍රිකෝණයක සම්මත අංකනයට අනුව මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'-2ab\sin C',
        r'2bc\sin A',
        r'-2ac\sin B',
        r'2ab\cos C',
        r'-2bc\sin \frac A 2',
      ],
      'answer': r'2bc\sin A',
      'coins': 30,
      'xp': 100,
      'answerBuyCoins': (30*2.6).ceil(),
    },
    'question3': {
      'question': {
        'firstLine': r'\mathbf{(a - b)^2\cos^2 \frac C 2 + (a + b)^2\sin^2 \frac C 2}',
        'thirdLine': 'සාධාරන ත්‍රිකෝණයක සම්මත අංකනයට අනුව මෙම ප්‍රකාශය සමාන වනුයේ පහත කුමන ප්‍රකාශයටද?',
      },
      'answers': [
        r'(a^2 + b^2) - 2ab\sin C',
        r'(a^2 + b^2) - 2ab\sin\Big(\frac {A + B} 2\Big)',
        r'\frac {a^2 + b^2 + c^2} {2ab}',
        r'2(a^2 + b^2) - c^2',
        r'c^2',
      ],
      'answer': r'c^2',
      'coins': 35,
      'xp': 120,
      'answerBuyCoins': (35*2.6).ceil(),
    },
    'question4': {
      'question': {
        'firstLine': r'\mathbf{a(\cos B + \cos C)}',
        'thirdLine': 'සාධාරන ත්‍රිකෝණයක සම්මත අංකනයට අනුව මෙම ප්‍රකාශය පහත කුමකට සමාන වේද?',
      },
      'answers': [
        r'2(b + c)\sin^2\frac A 2',
        r'2(b - c)\sin^2 A',
        r'2a\sin^2\Big(\frac {B + C} 2\Big)',
        r'(b - c)\sin^2\frac A 2',
        r'\frac 1 2 (b - c)\sin^2\frac A 2',
      ],
      'answer': r'2(b + c)\sin^2\frac A 2',
      'coins': 40,
      'xp': 150,
      'answerBuyCoins': (40*2.6).ceil(),
    },
    'question5': {
      'question': {
        'firstLine': r'\mathbf{(b + c - a)\Big(\cot\frac B 2 + \cot\frac C 2\Big)}',
        'thirdLine': 'සාධාරන ත්‍රිකෝණයක සම්මත අංකනයට අනුව මෙම ප්‍රකාශය පහත කුමකට සමාන වේද?',
      },
      'answers': [
        r'bc\cot A',
        r'a\tan A',
        r'2a\cot\frac A 2',
        r'a\cot\frac A 2',
        r'abc\cot\frac A 2',
      ],
      'answer': r'2a\cot\frac A 2',
      'coins': 55,
      'xp': 200,
      'answerBuyCoins': (55*2.6).ceil(),
    },
  },
};
